"""Builds notebooks/model_training.ipynb (plain JSON, no extra libraries needed)."""
import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(BASE, "notebooks", "model_training.ipynb")


def md(src):
    return {"cell_type": "markdown", "metadata": {}, "source": src}


def code(src):
    return {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [], "source": src}


cells = [
    md("# Adaptive Aptitude Test Engine - Student Level Model\n\n"
       "Trains a **Random Forest** classifier on the self-generated `student_performance.csv` "
       "(9,600 rows) to predict a learner's level: **Beginner / Intermediate / Advanced**.\n\n"
       "Target accuracy band: **80 - 85 %** (realistic, not overfit)."),
    md("## 1. Imports"),
    code("import json\nimport joblib\nimport numpy as np\nimport pandas as pd\n"
         "import matplotlib.pyplot as plt\nimport seaborn as sns\n\n"
         "from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold\n"
         "from sklearn.ensemble import RandomForestClassifier\n"
         "from sklearn.metrics import accuracy_score, classification_report, confusion_matrix\n\n"
         "sns.set_theme(style='darkgrid')\npd.set_option('display.max_columns', 30)"),
    md("## 2. Load the dataset\nGenerated by `scripts/generate_student_performance.py` - not downloaded from Kaggle."),
    code("df = pd.read_csv('../data/student_performance.csv')\nprint(df.shape)\ndf.head()"),
    code("df.info()"),
    code("df.describe().T"),
    md("## 3. Data quality checks"),
    code("print('Missing values:\\n', df.isnull().sum())\nprint('\\nDuplicate rows:', df.duplicated().sum())"),
    md("## 4. Exploratory analysis"),
    code("plt.figure(figsize=(6,4))\nsns.countplot(x='level', data=df, order=['Beginner','Intermediate','Advanced'], palette='viridis')\n"
         "plt.title('Level distribution')\nplt.show()\n\ndf['level'].value_counts(normalize=True).round(3)"),
    code("fig, axes = plt.subplots(2, 2, figsize=(12, 8))\n"
         "for ax, col in zip(axes.flat, ['quant_accuracy','logical_accuracy','verbal_accuracy','di_accuracy']):\n"
         "    sns.boxplot(x='level', y=col, data=df, order=['Beginner','Intermediate','Advanced'], ax=ax, palette='mako')\n"
         "    ax.set_title(col)\nplt.tight_layout()\nplt.show()"),
    code("plt.figure(figsize=(11,8))\nsns.heatmap(df.drop(columns=['student_id','level']).corr(), annot=True, fmt='.2f', cmap='coolwarm')\n"
         "plt.title('Feature correlation')\nplt.show()"),
    md("## 5. Features and target"),
    code("FEATURES = [\n    'tests_taken', 'quant_accuracy', 'logical_accuracy', 'verbal_accuracy', 'di_accuracy',\n"
         "    'avg_time_per_question', 'attempted_ratio', 'easy_accuracy', 'medium_accuracy',\n"
         "    'hard_accuracy', 'retake_count', 'consistency_score', 'overall_accuracy',\n]\n"
         "TARGET = 'level'\n\nX = df[FEATURES]\ny = df[TARGET]\n\n"
         "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)\n"
         "print('Train:', X_train.shape, ' Test:', X_test.shape)"),
    md("## 6. Train the Random Forest\nDepth and leaf size are constrained so the forest generalises "
       "instead of memorising label noise."),
    code("model = RandomForestClassifier(\n    n_estimators=180,\n    max_depth=7,\n    min_samples_split=12,\n"
         "    min_samples_leaf=6,\n    max_features='sqrt',\n    class_weight='balanced',\n    random_state=42,\n    n_jobs=-1,\n)\n"
         "model.fit(X_train, y_train)"),
    md("## 7. Accuracy"),
    code("y_pred = model.predict(X_test)\nacc = accuracy_score(y_test, y_pred)\n"
         "print(f'Test accuracy: {acc*100:.2f}%')\n"
         "print('Train accuracy: {:.2f}%'.format(accuracy_score(y_train, model.predict(X_train))*100))\n\n"
         "assert 0.80 <= acc <= 0.85, 'Accuracy outside the 80-85% target band'"),
    code("cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n"
         "scores = cross_val_score(model, X, y, cv=cv, scoring='accuracy')\n"
         "print('5-fold CV accuracy:', (scores*100).round(2), ' mean = %.2f%%' % (scores.mean()*100))"),
    code("print(classification_report(y_test, y_pred))"),
    code("labels = ['Beginner','Intermediate','Advanced']\ncm = confusion_matrix(y_test, y_pred, labels=labels)\n"
         "plt.figure(figsize=(6,5))\nsns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=labels, yticklabels=labels)\n"
         "plt.xlabel('Predicted'); plt.ylabel('Actual'); plt.title('Confusion matrix')\nplt.show()"),
    md("## 8. Feature importance"),
    code("imp = pd.Series(model.feature_importances_, index=FEATURES).sort_values()\n"
         "plt.figure(figsize=(8,6))\nimp.plot(kind='barh', color='#6366f1')\nplt.title('Random Forest feature importance')\nplt.show()"),
    md("## 9. Sample prediction"),
    code("sample = pd.DataFrame([{\n    'tests_taken': 3, 'quant_accuracy': 71.4, 'logical_accuracy': 66.7, 'verbal_accuracy': 75.0,\n"
         "    'di_accuracy': 33.3, 'avg_time_per_question': 48, 'attempted_ratio': 100, 'easy_accuracy': 85,\n"
         "    'medium_accuracy': 62, 'hard_accuracy': 40, 'retake_count': 1, 'consistency_score': 58.3,\n"
         "    'overall_accuracy': 65.0,\n}])[FEATURES]\n"
         "print('Predicted level:', model.predict(sample)[0])\n"
         "print(dict(zip(model.classes_, model.predict_proba(sample)[0].round(3))))"),
    md("## 10. Save the model for the Flask app"),
    code("bundle = {'model': model, 'features': FEATURES, 'classes': list(model.classes_), 'accuracy': round(float(acc), 4)}\n"
         "joblib.dump(bundle, '../ml/rf_level_model.pkl')\n\n"
         "with open('../ml/metrics.json', 'w') as f:\n"
         "    json.dump({'accuracy': round(acc*100, 2), 'n_rows': int(df.shape[0]), 'features': FEATURES,\n"
         "               'classes': list(model.classes_),\n"
         "               'report': classification_report(y_test, y_pred, output_dict=True)}, f, indent=2)\n"
         "print('Saved ../ml/rf_level_model.pkl')"),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)
print("Wrote", OUT)
